# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbbfe7d15c091343bc587104361dea9466f0c6c8edf5739cd66cc478f39fb002de3796a963814ff025b5e14396321b2baf022cec24e95699138ac2e4bc245478

test:
  secret_key_base: 1c30e4da4fee6bb894ab12399468f6c9d9777b52b2d59ebc42fc9ea2d8a5ee180de9d86169da6d808336a1ad5fb0e1dc25254b6bde4a1b8080df4e805837dd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
